name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_title: ${{ steps.release_info.outputs.release_title }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate Release Info
        id: release_info
        run: |
          RELEASE_TITLE=$(git describe --tags --abbrev=0)
          echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          RELEASE_TITLE="$RELEASE_TITLE" python cli/build/changelog.py >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.release_info.outputs.release_title }}
          body: ${{ steps.release_info.outputs.release_body }}
          tag: ${{ github.ref }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
